### ISSUE TITLE
add resolution label to the Personal Data view

### ISSUE THREAD

**Issue by ttunturi** [GEANT/shib-idp-profile#3]
The Personal Data view does not set a resolution label when resolving the user's attributes:

DEBUG [net.shibboleth.idp.attribute.resolver.impl.AttributeResolverImpl:196] - Attribute Resolver 'ShibbolethAttributeResolver': Initiating attribute resolution with label: null

So you can't exclude some DataConnectors that will produce warnings into the logs:

WARN [net.shibboleth.idp.attribute.resolver.dc.impl.PairwiseIdDataConnector:260] - Data Connector 'pairwiseIdConnector': Could not get attribute recipient or group ID, skipping ID creation

**Comment by jalauros** [comment]
Implemented. Will be in the next release.
