### ISSUE TITLE
show principal type in the Activity Page

### ISSUE THREAD

**Issue by ttunturi** [GEANT/shib-idp-profile#7]
It would be useful to see the principal type that was used with the login in the Activity Page. To make it prettier on the eye and also for better fitment you would configure mappings for the principals like:

saml2/https://refeds.org/profile/mfa = mfa
oidc/https://refeds.org/profile/mfa = mfa
saml2/https://refeds.org/profile/sfa = sfa
oidc/https://refeds.org/profile/sfa = sfa
saml2/urn:oasis:names:tc:SAML:2.0:ac:classes:Kerberos = krb
saml2/urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport = pwd

And so forth. Or without the protocol specifier (saml2/oidc). Which ever is more convenient to use/access at that stage.

**Comment by jalauros** [comment]
Implemented. Will be in the next release.
